/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sklad;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adam
 */
public class DefinovanyMaterial extends javax.swing.JFrame {

    private final int firma;
    private final String nazev;
    Connection conn;
    
    public DefinovanyMaterial(int i,Connection c, String n, String t) {
        this.firma = i;
        this.conn = c;
        this.nazev = n;
        initComponents();
        this.setTitle(t);
        naplntabulku();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Název", "Firma", "Kategorie"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void naplntabulku(){
    PreparedStatement preparedStatement;
    String sql = "select * from APP.DEFINICE where FIRMA=?";
    ResultSet result;
    
        try {
            preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setInt(1, this.firma);
            result = preparedStatement.executeQuery();
            int pom = 0;
            
             while (result.next())
            {   
                Object[] row = new Object[3];
                
                for (int i = 1; i <= 3; i++)
                {
                  if (i==1){
                      row[i - 1] = result.getObject(i); 
                  }  
                  if (i==2){
                      row[i-1] = this.nazev;
                  }  
                  if (i==3){
                      
                      switch( Integer.parseInt( result.getObject(i).toString()) ){
                          case 1:
                              row[i-1] = "PM/ICD";
                              break;
                          case 2:
                              row[i-1] = "Elektroda";
                              break;                             
                          case 3:
                              row[i-1] = "Příslušenství";
                              break; }   
                  }  }
                
                ((DefaultTableModel) jTable1.getModel()).insertRow(pom,row);
                pom++;
            }
            
            result.close();
            preparedStatement.close();
            
              
        } catch (SQLException ex) {
            Logger.getLogger(DefinovanyMaterial.class.getName()).log(Level.SEVERE, null, ex);
        }    
    
    
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
