/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sklad;


import com.itextpdf.text.DocumentException;
import java.awt.EventQueue;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Adam
 */
public class HlavniOkno extends javax.swing.JFrame {

    private static String url; 
    Connection conn;
    private int VybranaFirma;
    private String VybranaFirma_nazev;
    private int pocetfirem;
    private  List<String> nazvy_materialu;
    private  List<Integer> kategorie_materialu;

    
    public HlavniOkno(String s) {
        HlavniOkno.url = s;
        initComponents();
        String sql = "SELECT * FROM APP.FIRMY";
   
    try{                  
        conn = DriverManager.getConnection(url,"adam","adam"); 
        Statement statement = conn.createStatement();
        ResultSet r =  statement.executeQuery(sql);
        while (r.next()){
          String pom =  r.getObject(2).toString();
          this.pocetfirem++;
          JMenuItem f = new JMenuItem(pom);
          f.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firmavybrana(evt);
            }
            });          
          jMenu2.add(f);
        }
  
        r.close();
        statement.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Nepodařilo se připojit k databázi");
            System.exit(0);  
        }         
        jTable1.getColumnModel().getColumn(7).setMinWidth(0);
        jTable1.getColumnModel().getColumn(7).setMaxWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        label1 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        label2 = new java.awt.Label();
        textField2 = new java.awt.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SKLAD KARDIOSTIMULAČNÍ TECHNIKY");
        setName("SKLAD KARDIOSTIMULAČNÍ TECHNIKY"); // NOI18N
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Vyber firmu");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Definice materiálu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Definovat nový");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Přehled definic");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Příjem/Výdej materiálu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(165, 113));

        jButton2.setText("Vydat materiál");
        jButton2.setMaximumSize(new java.awt.Dimension(119, 25));
        jButton2.setMinimumSize(new java.awt.Dimension(119, 25));
        jButton2.setPreferredSize(new java.awt.Dimension(119, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Tisk výdejky");
        jButton3.setMaximumSize(new java.awt.Dimension(119, 25));
        jButton3.setMinimumSize(new java.awt.Dimension(119, 25));
        jButton3.setPreferredSize(new java.awt.Dimension(119, 25));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Příjem materiálu");
        jButton4.setMaximumSize(new java.awt.Dimension(119, 25));
        jButton4.setMinimumSize(new java.awt.Dimension(119, 25));
        jButton4.setPreferredSize(new java.awt.Dimension(119, 25));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        label1.setText("Poslední výdejka:");

        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });

        label2.setText("Počet kusů:");

        textField2.setText("1");
        textField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addComponent(textField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Název", "SN/LOT", "Dodací list", "Datum přijetí", "Počet", "Expirace", "", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setRowHeight(25);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel1);

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem2.setText("Přidat novou firmu");
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem1.setText("Close");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Verze 29.6.2017");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Výběr Firmy");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
//ukonceni
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {                                                                                               //ukonceni
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(HlavniOkno.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
       
    }//GEN-LAST:event_jMenu2ActionPerformed
 // PDF
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        Calendar cal = Calendar.getInstance();
        int rok = cal.get(Calendar.YEAR);
        java.sql.Date ted = konvertuj(cal.getTime());
        cal.clear();
        cal.set(rok, 0, 1);
        java.sql.Date prvniden = konvertuj(cal.getTime());
        
        PDFdocument dokument = new PDFdocument();
        dokument.opendoc();
        try {
            dokument.hlavicka();
            dokument.vydejka(("Výdejka číslo "+this.textField1.getText()+"/"),this.datumvydejky(Integer.parseInt(this.textField1.getText())));
            dokument.adresa(this.getadr(this.VybranaFirma));

            String sql = "Select NAZEV,SN,DL,POCET,VYDANI FROM APP.SKLAD WHERE FIRMA=? AND KATEGORIE=? AND VYDEJKA=? AND VYDANI between ? and ? ORDER BY NAZEV";
            PreparedStatement ps = conn.prepareStatement(sql,ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ps.setInt(1, this.VybranaFirma);
            ps.setInt(3, Integer.parseInt(this.textField1.getText()));
            ps.setDate(4, prvniden);
            ps.setDate(5, ted);
            for (int i=1;i<4;i++){
                ps.setInt(2, i);
                ResultSet rs = ps.executeQuery();
                switch (i) {
                    case 1:
                        dokument.datatabulky("PM/ICD", rs);
                        break;
                    case 2:
                        dokument.datatabulky("Elektrody", rs);
                        break;    
                    case 3:                       
                        dokument.datatabulky("Příslušenství", rs);
                        break;                         
                } rs.close(); }   ps.close();
            dokument.celkove();
            dokument.closedoc();   
        } catch (DocumentException | SQLException ex) {
            Logger.getLogger(HlavniOkno.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(this, "Soubor uložen");

    }//GEN-LAST:event_jButton3ActionPerformed
// nova definice materialu
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      final NovaDefinice definuj = new NovaDefinice(this.VybranaFirma, this.conn);        // nova definice materialu
//      java.awt.EventQueue.invokeLater(() -> {
//          definuj.setVisible(true);
//      });
           EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                definuj.setVisible(true);
            }
        });  
    }//GEN-LAST:event_jButton1ActionPerformed
// prehled definic materialu
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      final DefinovanyMaterial d = new DefinovanyMaterial(this.VybranaFirma,this.conn,this.VybranaFirma_nazev, "Přehled materiálu firmy "+this.VybranaFirma_nazev);   //prehled definic materialu
//      java.awt.EventQueue.invokeLater(() -> {
//          d.setVisible(true);
//      });
           EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                d.setVisible(true);
            }
        });       
      
    }//GEN-LAST:event_jButton5ActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void textField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField2ActionPerformed
//prijem materialu
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                          
     int pocet = Integer.parseInt(textField2.getText());
     final Prijem okno = new Prijem(pocet, nazvy_materialu,kategorie_materialu, this.conn, this.VybranaFirma,this.posledniid()); 
     okno.addWindowListener(new WindowAdapter() {
        @Override
        public void windowClosed(WindowEvent event) {
            naplntabulku();
           }
        });     
     
//       java.awt.EventQueue.invokeLater(() -> {
//           okno.setVisible(true);
//    });     
          EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                okno.setVisible(true);
            }
        }); 
        
    }//GEN-LAST:event_jButton4ActionPerformed
// Vydej materialu
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int x = jTable1.getRowCount();
       List<Integer> b = new ArrayList<Integer>();       
       
       for (int i=0;i<x;i++){
           if ( jTable1.getModel().getValueAt(i, 6).equals(true)){
               b.add((Integer) jTable1.getModel().getValueAt(i, 7));
           }
       }     
      
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Opravdu vydat "+b.size()+" ks materiálu?", "Prosím potvrďte", dialogButton);
        if(dialogResult == 0) {     
       
      String sql = "UPDATE APP.SKLAD SET VYDEJKA=?, VYDANI=? WHERE ID=?"; 
        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, Integer.parseInt(this.textField1.getText().toString())+1);
            
            Calendar cal = Calendar.getInstance();
            java.util.Date d =  cal.getTime();
            ps.setDate(2, this.konvertuj(d) );
            for (int i=0;i<b.size();i++){
                ps.setInt(3, b.get(i));
                ps.executeUpdate();
            }
            ps.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(HlavniOkno.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.naplntabulku();
        this.zjistivydejku();
         } 
   
        
    }//GEN-LAST:event_jButton2ActionPerformed
// reakce na pravy mysoklik - update SN nebo nazvu
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
              if ( SwingUtilities.isRightMouseButton(evt) ){

                    int c = jTable1.columnAtPoint(new Point(evt.getX(), evt.getY()));
                    int r = jTable1.rowAtPoint(new Point(evt.getX(), evt.getY()));
                    int id = (int) jTable1.getValueAt(r, 7);
                    if (c<2){    
                    rklikmenu menu = new rklikmenu(c,id,this.nazvy_materialu, this.conn);
                    menu.show(evt.getComponent(), evt.getX(), evt.getY());                   
                    menu.getn().addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosed(WindowEvent event) {
                        naplntabulku();
                        }
                    });
                } 
              }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

//vyber firmy z menu
    private void firmavybrana(java.awt.event.ActionEvent evt) {
        JMenuItem item = (JMenuItem)evt.getSource();
        this.VybranaFirma_nazev = item.getText();
        jLabel1.setText(item.getText());
        for (int i=0;i<this.pocetfirem;i++){
            if(this.jMenu2.getItem(i) == item ){
              this.VybranaFirma = i+1;
            }            
        }
        this.naplnlist();
        this.naplntabulku();
        this.zjistivydejku();
    }
//zobrazeni v tabulce    
    private void naplntabulku() { 
     int columns = 7;
     String sql = "select * from APP.nasklade WHERE FIRMA=?";
     while (jTable1.getRowCount() > 0) {
                ((DefaultTableModel) jTable1.getModel()).removeRow(0);
            }      
     try {
          PreparedStatement ps = conn.prepareStatement(sql);  
          ps.setInt(1, this.VybranaFirma);
          ResultSet rs = ps.executeQuery();
          int pom = 0;
            
          while (rs.next() ) {
              
              Object[] row = new Object[columns+1];
              
              for (int i = 1; i <= columns; i++)
                {
                  if (i==columns){
                      row[i-1] = Boolean.FALSE;
                      row[i] = rs.getObject(i+1); 
                  } else {
                      
                   if (rs.getObject(i+1) instanceof java.sql.Date ) {  
                    row[i - 1] = konvertuj2((java.sql.Date)rs.getObject(i+1)); } else {
                    row[i-1] = rs.getObject(i+1); 
                   }
                   
                }
                }          
              
              ((DefaultTableModel) jTable1.getModel()).insertRow(pom,row);
               pom++;             
          }  
            
        ps.close();
        rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(HlavniOkno.class.getName()).log(Level.SEVERE, null, ex);
        }    
     TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(jTable1.getModel());
     jTable1.setRowSorter(sorter);
     jTable1.updateUI();
        
    }
//posledni cislo vydejky    
    private void zjistivydejku(){
        Calendar cal = Calendar.getInstance();
        int rok = cal.get(Calendar.YEAR);
        java.sql.Date ted = konvertuj(cal.getTime());
        cal.clear();
        cal.set(rok, 0, 1);
        java.sql.Date prvniden = konvertuj(cal.getTime());

        String sql = "select VYDANI,VYDEJKA from APP.sklad WHERE FIRMA=? and VYDANI between ? and ? AND VYDEJKA is not null order by VYDEJKA";
        try {
            
            PreparedStatement ps = conn.prepareStatement(sql,ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ps.setInt(1, this.VybranaFirma);
            ps.setDate(2, prvniden);
            ps.setDate(3, ted);
            ResultSet rs = ps.executeQuery(); 

            if ( rs.last() == false ) {
                this.textField1.setText("0"); } else {
                this.textField1.setText(rs.getObject(2).toString());
            }
            rs.close();
            ps.close();            
        } catch (SQLException ex) {
            Logger.getLogger(HlavniOkno.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
//posledni prvek v databazi    
    private int posledniid(){
       String sql = "select ID from APP.SKLAD order by ID";
       int o = 0;
        try {
            
            PreparedStatement ps = conn.prepareStatement(sql,ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = ps.executeQuery(); 
            if ( rs.last() == false ) {
                o=0; } else {
                o= (Integer)rs.getObject(1);}
            rs.close();
            ps.close();  
        } catch (SQLException ex) {
            Logger.getLogger(HlavniOkno.class.getName()).log(Level.SEVERE, null, ex);
        } 
        return o;
    }
//konverze data do sql formatu    
    private java.sql.Date konvertuj(java.util.Date d){
         DateFormat output = new SimpleDateFormat("yyyy-MM-dd");
         String d2 = output.format(d);
         java.util.Date out = null;
           try {
             out = output.parse(d2);
           } catch (ParseException ex) {
               Logger.getLogger(Prijem.class.getName()).log(Level.SEVERE, null, ex);
           }
          java.sql.Date sqlDate = new java.sql.Date(out.getTime());    
    
    
    return sqlDate;        
}
//konverze sql data do string data    
    private String konvertuj2(java.sql.Date d){
         DateFormat output = new SimpleDateFormat("dd. MM. yyyy");
         String d2 = output.format(d);    
    return d2;        
}    
//zjisteni adresy z databaze
    private String[] getadr(int f) {
            String[] vysledek = {"","",""};
            String sql = "select * from APP.FIRMY WHERE ID=?";
        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, f);
            ResultSet rs = ps.executeQuery();
            rs.next();
            vysledek[0] = rs.getString(2);
            vysledek[1] = rs.getString(3);
            vysledek[2] = rs.getString(5)+"  "+rs.getString(4);
            ps.close();
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(HlavniOkno.class.getName()).log(Level.SEVERE, null, ex);
        }
        return vysledek;
    }
//datum vybrane vydejky
    private String datumvydejky(int v) {
        Calendar cal = Calendar.getInstance();
        int rok = cal.get(Calendar.YEAR);
        java.sql.Date ted = konvertuj(cal.getTime());
        cal.clear();
        cal.set(rok, 0, 1);
        java.sql.Date prvniden = konvertuj(cal.getTime());
        
        String sql = "select VYDANI from APP.SKLAD WHERE FIRMA=? AND VYDEJKA=? AND VYDANI between ? and ?";
        java.sql.Date out = null;
          try {
            
            PreparedStatement ps = conn.prepareStatement(sql,ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ps.setInt(1, this.VybranaFirma);
            ps.setInt(2, v);
            ps.setDate(3, prvniden);
            ps.setDate(4, ted);           
            
            ResultSet rs = ps.executeQuery(); 
            rs.next();
            out = (java.sql.Date)rs.getObject(1);

            rs.close();
            ps.close();            
        } catch (SQLException ex) {
            Logger.getLogger(HlavniOkno.class.getName()).log(Level.SEVERE, null, ex);
        }      
        
        return this.konvertuj2(out);       
    }
    
//naplneni definic
    private void naplnlist() {
        PreparedStatement preparedStatement;
        String sql = "select * from APP.DEFINICE where FIRMA=?";
        ResultSet result;
        List<String> n_m = new ArrayList<String>(); 
        List<Integer> k_m = new ArrayList<Integer>(); 
    
        try {
            preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setInt(1, this.VybranaFirma);
            result = preparedStatement.executeQuery();
            
             while (result.next())
            {   
                n_m.add(result.getObject(1).toString());
                k_m.add( Integer.parseInt( result.getObject(3).toString()) );
            }
             
            result.close();
            preparedStatement.close();              
        } catch (SQLException ex) {
            Logger.getLogger(HlavniOkno.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.nazvy_materialu = n_m;
        this.kategorie_materialu = k_m;
    }
    
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    // End of variables declaration//GEN-END:variables
}
