/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sklad;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Adam
 */
public class Prijem extends javax.swing.JFrame {
    private final int pocet;
    private final int firma;
    private final int lastid;
    private final List<String> nazvy_materialu;
    private final List<Integer> kategorie_materialu;
    Connection conn;
 
    public Prijem(int i, List<String> l,List<Integer> m,Connection c, int f, int id) {
        this.pocet = i;
        this.nazvy_materialu = l;
        this.kategorie_materialu = m;
        this.conn =c;
        this.firma = f;
        this.lastid = id;
        initComponents();       
        initpanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Příjem nového materiálu na sklad");
        setResizable(false);
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0};
        layout.rowHeights = new int[] {0, 20, 0, 20, 0};
        getContentPane().setLayout(layout);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(0, 650));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(jPanel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 40, 0, 40, 0, 40, 0, 40, 0};
        jPanel2Layout.rowHeights = new int[] {0, 8, 0, 8, 0, 8, 0};
        jPanel2.setLayout(jPanel2Layout);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Potvrdit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(jButton1, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Dodací list");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(jLabel1, gridBagConstraints);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField1.setPreferredSize(new java.awt.Dimension(6, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 2.5;
        jPanel2.add(jTextField1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Datum");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(jLabel2, gridBagConstraints);

        jSpinner1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerDateModel());
        jSpinner1.setEditor(new javax.swing.JSpinner.DateEditor(jSpinner1, "dd.MM.yyyy"));
        jSpinner1.setPreferredSize(new java.awt.Dimension(109, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(jSpinner1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String insert = "INSERT INTO APP.SKLAD (FIRMA,NAZEV,SN,DL,PRIJETI,POCET,EXPIRACE,KATEGORIE,ID) VALUES(?,?,?,?,?,?,?,?,?)"; 
        try {           
            PreparedStatement ps = conn.prepareStatement(insert);
            ps.setInt(1,this.firma);
            ps.setDate(5, konvertuj((Date)this.jSpinner1.getValue()));
            ps.setString(4, this.jTextField1.getText());
            for (int i=0;i<this.pocet;i++){
               panel_prijem akt_panel = (panel_prijem) jPanel1.getComponent(i);
               ps.setString(2,akt_panel.getnazev());
               ps.setString(3, akt_panel.getsn());
               ps.setInt(6, akt_panel.getpocet());
               if (akt_panel.stavexpirace()){
                    ps.setDate(7, konvertuj(akt_panel.getdate()));}
               else {
                    ps.setDate(7, null);
               }
               ps.setInt(8, this.kategorie_materialu.get(this.nazvy_materialu.indexOf(akt_panel.getnazev()))); 
               ps.setInt(9,i+this.lastid+1);
               ps.executeUpdate();
            }
            
            ps.close();
        } catch (SQLException ex) {
            Logger.getLogger(Prijem.class.getName()).log(Level.SEVERE, null, ex);
        }
        
     this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void initpanels(){
        
         for (int a=0; a<pocet;a++){
           panel_prijem x = new panel_prijem(this.nazvy_materialu);  
           jPanel1.add(x, a); 
        }
         if (jPanel1.getPreferredSize().getHeight() > 650){
             jScrollPane1.setPreferredSize(new Dimension(607,640));
         }

        this.pack();       
    }
    
private java.sql.Date konvertuj(Date d){
         DateFormat output = new SimpleDateFormat("yyyy-MM-dd");
         String d2 = output.format(d);
         Date out = null;
           try {
             out = output.parse(d2);
           } catch (ParseException ex) {
               Logger.getLogger(Prijem.class.getName()).log(Level.SEVERE, null, ex);
           }
          java.sql.Date sqlDate = new java.sql.Date(out.getTime());    
    
    
    return sqlDate;        
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
